# Generated by Django 2.2.9 on 2020-01-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='minimum_access_level',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('free', 'Free')], default=('gold', 'Gold'), max_length=6),
        ),
    ]
