# Generated by Django 2.2.9 on 2021-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200108_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='minimum_access_level',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze')], default=('gold', 'Gold'), max_length=6),
        ),
    ]
